[workspace]

members = [
    "yew_router",
    "crates/yew_router_route_parser",
    "crates/yew_router_macro",
    "examples/routing_component",
    "examples/guide",
    "examples/nested_routers"
]

