[workspace]

members = [
    "yew_router_route_parser",
    "yew_router_route_macro_impl",
    "yew_router_derive",
    "yew_router_from_matches_macro_impl",
    "yew_router",
    "yew_router_path_matcher", # This is only separate from route_parser because of some obscure linker bug involving emscriptem in yew interfering with proc macro definitions.
    "integration_test",
    "examples/routing_component",
    "examples/guide",
    "examples/nested_routers"
]

