[workspace]

members = [
    "yew_router_route_parser",
    "yew_router_route_macro_impl",
    "yew_router_derive",
    "yew_router_from_matches_macro_impl",
    "test_case1",
    "YewRouter",
    "integration_test"
]

