[package]
name = "yew_router"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT"


[features]
default = ["core", "unit_alias"]

core = ["router", "components", "matchers"]

unit_alias = []

router = ["agent", "yew_router_route_parser"]
components = ["agent" ]

agent = []
matchers = [ "regex_matcher", "route_matcher", "proc-macro-hack"]
regex_matcher = ["regex"]
route_matcher = ["yew_router_route_parser", "yew_router_macro", "nom"]


[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
yew = "0.9.0"
stdweb = "0.4"

yew_router_route_parser = {path = "crates/yew_router_route_parser", optional=true}
yew_router_macro = {path = "crates/yew_router_macro", optional=true}
nom = {version = "5.0.0", optional=true}
regex = {version = "1.3.1", optional=true}
proc-macro-hack = {version = "0.5.9", optional=true}


[workspace]

members = [
    "crates/yew_router_route_parser",
    "crates/yew_router_macro",
    "examples/routing_component",
    "examples/guide",
    "examples/nested_routers"
]

