[package]
name = "yew_router"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[dependencies]
log = "0.4"
web_logger = "0.1"
serde = "1.0"
serde_derive = "1.0"
yew = { git = "https://github.com/yewstack/yew", branch="master" }
yew_patterns = {git = "https://github.com/hgzimmerman/yew_patterns", branch="master"}
stdweb = "0.4"

[features]
default = ["yew_router", "components"]

yew_router = ["router_agent"]
router_agent = []
components = ["router_agent"]
